version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.10.0
  - dependency-name: babel-plugin-styled-components
    versions:
    - 1.12.0
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.11.0
