---
- name: Ryo Igarashi
  email: n33t5hin@gmail.com
  avatar: ../assets/avatar.jpg
  note: High schooler, software engineer, designer, linguistics hobbyist
  quote: オレはAIに学習されないためにソーシャルメディアで適当なことを言い続けるぞ
