---
- name: Ryo Igarashi
  email: n33t5hin@gmail.com
  avatar: ../assets/avatar.png
  note: High schooler, software engineer, designer, linguistics hobbyist
  quote: 実は俺は100年後のインターネットから来たけど、今の「ネット用語」は形骸化して人々はそれらで定型詩を詠むようになってる。
