---
- name: Pronouns
  label: he/him
  image: ../assets/male-symbol.png
  url: https://pronoun.is/he

- name: Nation
  label: Japan
  image: ../assets/japan.png
  url: https://www.japan.go.jp

- name: 2nd languages
  label: English, Mandarin
  image: ../assets/globe.png

- name: Favourite drink
  label: Chai
  image: ../assets/chai.png
  url: https://en.wikipedia.org/wiki/Masala_chai

- name: Workstation
  label: Macbook Pro
  image: ../assets/computer.png

- name: Waifu
  label: Nino Nakano
  image: ../assets/nino.png
  url: https://5hanayome.fandom.com/wiki/Nino_Nakano
