---
- name: Pronouns
  value: he/him
  image: ../assets/male-symbol.png

- name: Nation
  value: Japan
  image: ../assets/japan.png

- name: 2nd languages
  value: English, Mandarin
  image: ../assets/globe.png

- name: Favourite drink
  value: Chai
  image: ../assets/chai.png

- name: Workstation
  value: Macbook Pro
  image: ../assets/computer.png

- name: Waifu
  value: Nakano Nino
  image: ../assets/nino.png
