---
- title: neet.love
  description: Portfolio and blog, hosted by Ryo Igarashi
  author:
    name: Ryo Igarashi
    email: n33t5hin@gmail.com
    avatar: ../assets/avatar.jpg
    note: High schooler, web engineer, designer
    quote: 実は俺がインターネットなのではないかと思ってきた。
