---
- name:   Mastodon
  label:  "@neet@mastodon.social"
  href:   https://mastodon.social/@neet
  fa:     fab fa-mastodon
  color1: '#297ccd'
  color2: white
  tag:    social

- name:   Email
  label:  n33t5hin@gmail.com
  href:   mailto:n33t5hin@gmail.com
  fa:     fas fa-envelope
  color1: '#1981e0'
  color2: white
  tag:    social

- name:   Discord
  label:  '@neetshin#1400'
  copy:   neetshin#1400
  fa:     fab fa-discord
  color1: '#7289da'
  color2: white
  tag:    social

- name:   Telegram
  label:  '@neetshin'
  href:   https://t.me/neetshin
  fa:     fab fa-telegram-plane
  color1: '#2ca5e0'
  color2: white
  tag:    social

- name:   Twitter
  label:  "@TheGodOfNeet"
  href:   https://twitter.com/thegodofneet
  fa:     fab fa-twitter
  color1: '#1a97f0'
  color2: white
  tag:    social

- name:   Wantedly
  label:  "62403069"
  href:   https://www.wantedly.com/users/62403069
  fa:     fab fa-wikipedia-w # Wikipedia? never mind
  color1: '#00a4bb'
  color2: white
  tag:    social

- name:   GitHub
  label:  "@neet"
  href:   https://github.com/neet
  fa:     fab fa-github
  color1: black
  color2: white
  tag:    dev

- name:   GitLab.com
  label:  '@neetshin'
  href:   https://gitlab.com/neetshin
  fa:     fab fa-gitlab
  color1: '#de3a25'
  color2: white
  tag:    dev

- name:   Medium
  label:  "@neetshin"
  href:   https://medium.com/@neetshin
  fa:     fab fa-medium-m
  color1: white
  color2: black
  tag:    dev

- name:   SlideShare
  label:  ssuser881c4e
  href:   https://www.slideshare.net/ssuser881c4e
  fa:     fab fa-slideshare
  color1: '#0077b5'
  color2: white
  tag:    dev

- name:   NPM
  label:  neetshin
  href:   https://www.npmjs.com/~neetshin
  fa:     fab fa-npm
  color1: '#cb3837'
  color2: white
  tag:    dev

- name:   Docker Hub
  label:  neetshin
  href:   https://hub.docker.com/r/neetshin/
  fa:     fab fa-docker
  color1: '#1488c6'
  color2: white
  tag:    dev

- name:   Bitcoin
  label:  ''
  copy:   3AucsLDnY37qipYngLM5KH9heWkJ1AEArv
  fa:     fab fa-bitcoin
  color1: '#ff8e02'
  color2: white
  tag:    donate

- name:   Patreon
  label:  neetshin
  href:   https://www.patreon.com/neetshin
  fa:     fab fa-patreon
  color1: '#f96854'
  color2: white
  tag:    donate
