---
- name: Twitter
  icon: Twitter
  href: https://twitter.com/TheGodOfNeet
  username: '@TheGodOfNeet'

- name: Mastodon
  icon: Mastodon
  href: https://mastodon.social/@neet
  username: '@neet@mastodon.social'

- name: GitHub
  icon: GitHub
  href: https://github.com/neetshin
  username: '@neetshin'

- name: GitLab
  icon: GitLab
  href: https://gitlab.com/neetshin
  username: '@neetshin'

- name: Qiita
  icon: Qiita
  href: https://qiita.com/neetshin
  username: '@neetshin'

- name: NPM
  icon: NPM
  href: https://www.npmjs.com/~neetshin
  username: neetshin

- name: Patreon
  icon: Patreon
  href: https://www.patreon.com/neetshin
  username: neetshin

- name: Stack Overflow
  icon: Stack Overflow
  href: https://ja.stackoverflow.com/users/23391/neetshin
  username: neetshin

- name: Telegram
  icon: Telegram
  href: https://t.me/neetshin
  username: '@neetshin'

- name: Docker
  icon: Docker
  href: https://hub.docker.com/r/neetshin
  username: neetshin

- name: Flickr
  icon: Flickr
  href: https://www.flickr.com/photos/148366170@N04/
  username: neetshin

- name: Discord
  icon: Discord
  text: nucx#1400
  username: nucx#1400

- name: Medium
  icon: Medium
  href: https://medium.com/@neetshin
  username: '@neetshin'

- name: dev.to
  icon: devto
  href: https://dev.to/neetshin
  username: neetshin

- name: MDN
  icon: Mozilla
  href: https://developer.mozilla.org/ja/profiles/Neetshin
  username: Neetshin

- name: Bitcoin
  icon: Bitcoin
  text: 3AucsLDnY37qipYngLM5KH9heWkJ1AEArv
