---
- name: Lagune
  status: open
  description: |-
    Hackable desktop client for Mastodon and other related projects
    <https://github.com/lagunehq>

- name: Mastodon
  status: open
  description: |-
    Decentralized social networking platform.
    Contributed in web front end, Japanese localizeation and internationalization
    <https://joinmastodon.org>

- name: Halcyon
  status: close
  description: |-
    Web client for Mastodon with familiar interface
    <https://github.com/halcyon-suite/halcyon>
