- name: Twitter
  label: "@TheGodOfNeet"
  href: https://twitter.com/thegodofneet
  fa: fab fa-twitter

- name: Mastodon
  label: "@neet@mastodon.social"
  href: https://mastodon.social/@neet
  fa: fab fa-mastodon

- name: GitHub
  label: "@neet"
  href: https://github.com/neet
  fa: fab fa-github
