---
- name: NijiPico
  type: Web
  href: https://nijipi.co/
  description: 二次元とITのハイブリッドニュースサイト

- name: Halcyon
  type: Dev
  href: https://halcyon.social
  description: TwitterライクなMastodonクライアント (開発終了)

- name: Exotica
  type: Dev
  href: https://github.com/neetshin/exotica
  description: Mattermostクライアント (開発中)

- name: exotica-core
  href: https://github.com/neetshin/exotica-core
  description: JavaScript製Mattermost APIクライアント

- name: minazuki-bot
  href: https://github.com/neetshin/minazuki-bot
  description: Telegramチャットボット

- name: Opelete
  href: https://github.com/neetshin/opelete
  description: Googleの検索演算子を自動補完するブラウザ拡張
